version: "3.9"
services: 
    api:
        build:
            context: ./api
            dockerfile: ./docker/Dockerfile
        command: ./wait-for-postgres.sh db ./app
        depends_on: 
            - db
        environment: 
            DB_PASSWORD: ${DB_PASSWORD}
    client:
        build:
            context: ./client
            dockerfile: ./docker/Dockerfile
        ports: 
            - 80:80
        depends_on: 
            - api
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./api/schema/000001_init.up.sql:/docker-entrypoint-initdb.d/init.sql